# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Day Update

on:
  schedule:
    - cron: "15 21 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run
        run: ./gradlew run
      - name: Show
        run: |
          file_name=$(date "+%Y-%m").csv
          echo "---------- Additional Enchanted Miner ----------"
          cat "Additional Enchanted Miner/$file_name"
          echo "---------- Large Fluid Tank ----------"
          cat "Large Fluid Tank/$file_name"
          echo "---------- Scalable Cat's Force ----------"
          cat "Scalable Cat's Force/$file_name"
      - name: Git Commit
        run: |
          git config --local user.email "Kotori316@users.noreply.github.com"
          git config --local user.name "Kotori316"
          git commit -m $(date -I) -a
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
