# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Day Update

on:
  schedule:
    - cron: "15 21 * * *"
  workflow_dispatch:

jobs:
  update1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run
        run: ./gradlew run
        env:
          main_class: com.kotori316.dl.Main2
      - name: Show
        run: |
          file_name=$(date "+%Y-%m").csv
          echo
          echo "---------- Additional Enchanted Miner ----------"
          cat "Additional Enchanted Miner/$file_name"
          echo
          echo "---------- Large Fluid Tank ----------"
          cat "Large Fluid Tank/$file_name"
          echo
          echo "---------- Scalable Cat's Force ----------"
          cat "Scalable Cat's Force/$file_name"
      - name: Git Commit
        run: |
          git config --local user.email "Kotori316+action-bot@gmail.com"
          git config --local user.name "Kotori316+action-bot"
          git commit -m $(date -I) -a
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  update2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: RUN
        run: |
          Xvfb :99 -screen 0 1920x1080x16 &
          export DISPLAY=:99.0
          chmod +x gradlew && ./gradlew run
        env:
          main_class: com.kotori316.dl.Main
      - name: Show
        run: |
          file_name=$(date "+%Y-%m").csv
          echo
          echo "---------- Additional Enchanted Miner ----------"
          cat "additional-enchanted-miner/$file_name"
          echo
          echo "---------- Large Fluid Tank ----------"
          cat "largefluidtank/$file_name"
          echo
          echo "---------- Scalable Cat's Force ----------"
          cat "scalable-cats-force/$file_name"
      - name: Git Commit
        run: |
          git config --local user.email "Kotori316+action-bot@gmail.com"
          git config --local user.name "Kotori316+action-bot"
          git add .
          git commit -m $(date -I)
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
